Repository darwinai/covidnet_ui, pull requests merged in 2021-05, with the labels that each got.

#66 [CNXC-343] Display Series Description in dropdown for each study in PastAnalyses
  src/components/CreateAnalysis/ImageSelectionBox.tsx
  src/components/pastAnalysis/seriesTable.tsx
Labels: bug

#63 Remove fetchPluginInstanceFromId
  src/services/chris_integration.tsx
Labels: cleanup

#72 Fix typo in return type for function in chrisapi client
  src/types/chrisapi/index.d.ts
Labels: bug

#71 [CNXC-345] Show exact timestamp on Past Analysis Table for analyses finished within same day
  src/shared/utils.tsx
Labels: bug

#70 [CNXC-347] Reroute if series information is unavailable
  src/components/dicmViewer/dicomViewerBottomBox.tsx
Labels: bug

#69 [CNXC-253] Make login form remove error after failed login when values changed
  src/pages/LogIn/components/LoginForm.tsx
Labels: enhancement

#68 [CNXC-254] Implement loading UI for patient search
  src/components/PatientLookup.tsx
  src/pages/CreateAnalysisPage/CreateAnalysisPage.tsx
Labels: enhancement

#73 [CNXC-361] Move search error
  src/components/PatientLookup.tsx
Labels: bug
